# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml
#
# ### Variant 2: two line prompt, no background in top line, separators on left side

#
# - No filling solid line in top row: 
#   Replace '$fill\' with just one character '\' or just completely delete the line that contains '$fill\' further down,
#   within the format-block: format = """ ... """.
#
# - '$line_break': everything from the next line on refers to the second line of the prompt.
#
# - Some modules listed further down will not show up (all the time), as their default value is 'disabled = true' or
#   they are only displayed under certain conditions.
#
# - Symbols:
#   Don't be confused if you see this toml file via web browser on a website, gist, ... and you don't see any "real" symbols further down.
#   If Nerd-fonts are already installed on your system (e.g. MesloLG Nerd Font, FiraCode Nerd Font, ...) it should work.


# Customizing the prompt (and placing desired modules at desired position and sequence):
format = """
[â•­â•´](fg:#c0caf5)\
$os\
[](fg:#c0caf5 bg:#ffffff)\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$jobs\
$line_break\
[â•°â•´](fg:#c0caf5)\
[ï‘  ](fg:#bb9af7)\
"""

# Inserts a blank line between shell prompts:
add_newline = true


# Customization and activation of some modules:
# Listed in the order of their position in the module row above
[os]
format = " [$symbol]($style)[ ]()"
style = "fg:#c0caf5"
disabled = false

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ïŒƒ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "ğŸ‰"        # "î†"
Emscripten = "ğŸ”—"
EndeavourOS = "ïŒ¢"      # "ï»"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Garuda = "ï…¼"
Gentoo = "ïŒ"
HardenedBSD = "ï¦—"
Illumos = "ğŸ¦"
Linux = "ï…¼"
Macos = "ïŒ‚ "
Manjaro = "ïŒ’"
Mariner = "ï…¼"
MidnightBSD = "ğŸŒ˜"
Mint = "ïŒ"
NetBSD = "ï…¼"
NixOS = "ïŒ“"
OpenBSD = "ïŒ¨"          # "ï…¼"
OpenCloudOS = "â˜ï¸"
openEuler = "ï…¼"
openSUSE = "ïŒ”"
OracleLinux = "âŠ‚âŠƒ"
Pop = "ïŒª"              # "ï…¼"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Redox = "ğŸ§ª"
Solus = "ïŒ­"            # "ï…¼ "
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ï„ˆ"
Windows = "îœ"


[directory]
format = ' [](fg:cyan bold)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)'
style = 'fg:cyan bold'
home_symbol = '~'
read_only = 'ï ½ '
read_only_style = 'fg:cyan'
truncation_length = 2
truncation_symbol = 'â€¦/'
truncate_to_repo = false
repo_root_format = ' [](fg:cyan bold)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
repo_root_style = 'fg:cyan bold'
use_os_path_sep = true
disabled = false

[git_branch]
format = '[â¯ $symbol $branch(:$remote_branch)]($style)[ ]()'
style = 'fg:#E04D27'
symbol = 'î‚ '
#ignore_branches = ['master', 'main']

[git_commit]
format = '[\($hash$tag\)]($style)[ ]()'
style = 'fg:#E04D27'
commit_hash_length = 8
tag_symbol = 'ï’ '                       # 'ï€« ''
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ]()'
added_style = 'fg:#E04D27'
deleted_style = 'fg:#E04D27'
disabled = false

[git_status]
# place symbols before '$count'
format = '([$all_status$ahead_behind]($style))'
style = 'fg:#E04D27'
conflicted = '[ï‘¯${count} ](fg:red)'
ahead = '[â‡¡${count} ](fg:yellow)'
behind = '[â‡£${count} ](fg:yellow)'
diverged = '[â‡•${ahead_count}â‡¡${behind_count}â‡£ ](fg:yellow)' # â‡• â†• â‡³ ó°¹¹ ó°¹º ó°§ˆ 
up_to_date = '[âœ“ ](fg:green)'
untracked = '[ï° ${count} ](fg:red)'                         # 'ï° ' # '? '
stashed = '[ï’‡${count} ](fg:#A52A2A)'                        # 'ğŸ“¦ '# 'î› ' # 'ï’‡ ' # 'îœ ' # 'î¬‰ ' 
modified = '[ï‚­${count} ](fg:#C8AC00)'                       # 'ğŸ“' # '! ' # î # ï‚­ # ïƒ
staged = '[ïƒ‘$${count} ](fg:green)'                          # '+ '
renamed = '[ïƒŒ${count} ](fg:yellow)'                         # 'ï—ˆ ' # 'ï«¦' # á´‚ # ï¤ # ïƒ # ïƒŒ # ï³³
deleted = '[ï¯Š${count} ](fg:orange)'                         # 'ğŸ—‘ ' '- '
disabled = false

[jobs]
format = '[ î‚± ](fg:blue bold)[$number$symbol]($style)'
style = 'fg:blue'
symbol = 'ï¥­'                                           # 'ïª‚' # 'ó°œ' # 'î®¢' # 'âœ¦'
symbol_threshold = 1
number_threshold = 4
disabled = false


[cmd_duration]
format = '[î‚³ $duration ]($style)'
style = 'fg:yellow'
min_time = 500
disabled = false

[fill]
style = 'fg:#505050'
symbol = 'â”€'

[status]
format = '[$symbol$status $hex_status $signal_number-$signal_name ]($style)'
style = 'fg:red'
symbol = 'âœ˜ '
disabled = false

[localip]
format = '[$localipv4 ](fg:green bold)'
ssh_only = true
disabled = false
