format = """
$os\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status$python\
$jobs\
$line_break\
$character\
"""

add_newline = true

[os]
format = "[$symbol]($style)[]()"
# style = "fg:white"
disabled = false

[os.symbols]
Macos = ""
Arch = "󰣇"
Raspbian = ""

[character]
success_symbol = '[](bold cyan)'
error_symbol = '[](bold red)'

[directory]
format = ' [](fg:blue bold)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
style = 'fg:blue bold'
home_symbol = '~'
read_only = ' '
read_only_style = 'fg:orange'
truncation_length = 4
truncation_symbol = '../'
truncate_to_repo = false
repo_root_format = ' [](fg:blue bold)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
repo_root_style = 'fg:blue bold'
use_os_path_sep = true
disabled = false

[git_branch]
format = '[❯ $symbol $branch(:$remote_branch)]($style)[ ]()'
style = 'fg:cyan'
symbol = ''

[git_commit]
format = '[\($hash$tag\)]($style)[ ]()'
style = 'fg:yellow'
commit_hash_length = 8
tag_symbol = ' '
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ]()'
added_style = 'fg:green'
deleted_style = 'fg:red'
disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'fg:orange'
conflicted = '[${count} ](fg:red)'
ahead = '[⇡${count} ](fg:yellow)'
behind = '[⇣${count} ](fg:yellow)'
diverged = '[⇕${ahead_count}⇡${behind_count}⇣ ](fg:yellow)'
untracked = '[${count} ](fg:purple)'
stashed = '[${count} ](fg:blue)'
modified = '[${count} ](fg:yellow)'
staged = '[${count} ](fg:green)'
renamed = '[${count} ](fg:orange)'
deleted = '[${count} ](fg:red)'
disabled = false

[jobs]
format = '[ ❯ ](fg:cyan bold)[$number$symbol]($style)'
style = 'fg:cyan'
symbol = '󰜎'
symbol_threshold = 1
number_threshold = 4
disabled = false

[python]
format = '[(\($virtualenv\) )]($style)'

