format = """
$os\
[](fg:#c0caf5 bg:#ffffff)\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$jobs\
$line_break\
[â¯ ](fg:#76946A)\
"""

add_newline = true

[os]
format = "[$symbol]($style)[ ]()"
style = "fg:#e5ded4"
disabled = false

[os.symbols]
Arch = "ïŒƒ"
EndeavourOS = "ïŒ¢" # "ï»"
Linux = "ï…¼"
Macos = "ïŒ‚"
NixOS = "ïŒ“"
Ubuntu = "ïŒ›"
Unknown = "ï„ˆ"


[directory]
format = '[ ](fg:cyan bold)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
style = 'fg:cyan bold'
home_symbol = '~'
read_only = 'ï ½ '
read_only_style = 'fg:cyan'
truncation_length = 6
truncation_symbol = '../'
truncate_to_repo = false
repo_root_format = ' [](fg:cyan bold)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
repo_root_style = 'fg:cyan bold'
use_os_path_sep = true
disabled = false

[git_branch]
format = '[â¯ $symbol $branch(:$remote_branch)]($style)[ ]()'
style = 'fg:#E04D27'
symbol = 'î‚ '

[git_commit]
format = '[\($hash$tag\)]($style)[ ]()'
style = 'fg:#E04D27'
commit_hash_length = 8
tag_symbol = 'ï’ '
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ]()'
added_style = 'fg:#E04D27'
deleted_style = 'fg:#E04D27'
disabled = false

[git_status]
# place symbols before '$count'
format = '([$all_status$ahead_behind]($style))'
style = 'fg:#E04D27'
conflicted = '[ï‘¯ ${count} ](fg:red)'
ahead = '[â‡¡${count} ](fg:yellow)'
behind = '[â‡£${count} ](fg:yellow)'
diverged = '[â‡•${ahead_count}â‡¡${behind_count}â‡£ ](fg:yellow)'
up_to_date = '[âœ“ ](fg:green)'
untracked = '[ï° ${count} ](fg:red)'
stashed = '[ï’‡ ${count} ](fg:#A52A2A)'
modified = '[ï‚­ ${count} ](fg:#C8AC00)'
staged = '[ïƒ‘ ${count} ](fg:green)'
renamed = '[ïƒŒ ${count} ](fg:yellow)'
deleted = '[ğŸ—‘${count} ](fg:orange)'
disabled = false

[jobs]
format = '[â¯ ](fg:blue bold)[$number$symbol]($style)'
style = 'fg:blue'
symbol = 'ó°œ'
symbol_threshold = 1
number_threshold = 4
disabled = false

[fill]
style = 'fg:#938AA9'
symbol = ' '
