If:
  PathMatch: .*\.(c|h)$
CompileFlags:
  Compiler: /usr/bin/gcc

---

# Apply this config conditionally to all C++ files
If:
  PathMatch: .*\.(c|h)pp
CompileFlags:
  Compiler: /usr/bin/g++

---

# Apply this config conditionally to all CUDA files
If:
  PathMatch: .*\.cuh?
CompileFlags:
  Compiler: /opt/cuda/bin/nvcc
  Add:
    # report all errors
    - "-ferror-limit=0"
    - "-xcuda"
    - "-std=c++11"
    - --cuda-path=/opt/cuda
    - --cuda-gpu-arch=sm_61
    - -L/opt/cuda/lib64
    - -I/opt/cuda/include

---

# Tweak the clangd parse settings for all files
CompileFlags:
  Add:
    # report all errors
    - "-ferror-limit=0"
  Remove:
    # strip CUDA fatbin args
    - "-Xcompiler*"
    - "-Xfatbin*"
    # strip CUDA arch flags
    - "-gencode*"
    - "--generate-code*"
    # strip CUDA flags unknown to clang
    - "-ccbin*"
    - "--options-file*"
    - "--compiler-options*"
    - "--expt-extended-lambda"
    - "--expt-relaxed-constexpr"
    - "-forward-unknown-to-host-compiler"
    - "-Werror=cross-execution-space-call"
Hover:
  ShowAKA: No
InlayHints:
  Enabled: No
Diagnostics:
  Suppress:
    - "variadic_device_fn"
    - "attributes_not_allowed"
